version: 2.1

orbs:
  win: circleci/windows@2.0.0

jobs:
  build:
    executor:
      shell: powershell.exe
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "CalcMvcWeb/CalcMvcWeb.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
