version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  test:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "CalcMvcWeb/CalcMvcWeb.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "CalcMvcWeb/CalcMvcWeb.csproj" }}
      - run:
          name: "Run Application Tests"
          command: dotnet.exe test -v d
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe build --configuration Release
